/*
============================================================================
 Name		: mmp_common.inc
 Author	  : 
 Copyright   : 
 Description : Common project specification for container widget ECom plugin
 and static container widget library meant to be linked against EUnit unit tests.
============================================================================
*/

USERINCLUDE	 			      ../inc
MW_LAYER_SYSTEMINCLUDE

SOURCEPATH	  			      ../src
SOURCE		  			      alfcontainerwidgetfactoryplugin.cpp
SOURCE					      alfcontainerwidget.cpp
SOURCE						  alfcontainerwidgetexception.cpp
SOURCE						  alfcontainercontrol.cpp

USERINCLUDE             ../../../inc